Merge pull request #624 in EDD/edd-django from ~MARK.FORRER/edd-django:bugfix/EDD-1237-test-assay-metadata to master
Squashed commit of the following:

commit b0e6c237e18304dd7dc12b864b212317908f533d
Author: Mark Forrer <mark.forrer@lbl.gov>
Date:   Mon Mar 2 14:20:46 2020 -0800

    Added type annotations to aid maintenance / future refactoring

commit 2f54f92867cc3c0ef6f314b87b929acd58761a02
Author: Mark Forrer <mark.forrer@lbl.gov>
Date:   Thu Feb 27 14:42:50 2020 -0800

    Tested assay metadata parsing in ED files

    Added unit tests for parsing assay metadata from Experiment Description files, and separated out parser tests from existing integration tests.

    Now that it's enabled by unit tests, also did some targeted refactoring of existing EDD parser code related to assay metadata parsing.  Broke up long method _parse_assay_metadata_header, and moved error check from ColumnLayout.register_assay_metadata_col() into the parser instead to simplify method signature.  Added type annotations as encountered to help improve readability for future refactoring.

commit 5657aa7f53d110996703b8a106260b3e9227be22
Author: Mark Forrer <mark.forrer@lbl.gov>
Date:   Thu Feb 13 13:19:46 2020 -0800

    Removed Python 2 backward compatibility code

commit a425a3805c66a64a872001cb84e1285607295b1f
Author: Mark Forrer <mark.forrer@lbl.gov>
Date:   Tue Feb 25 10:30:18 2020 -0800

    Remove Python 2 backward compatibility code

commit e6cf817b225249d6aea5ca67ffc65d6ca62a1c61
Author: Mark Forrer <mark.forrer@lbl.gov>
Date:   Fri Feb 14 11:57:22 2020 -0800

    Fixed unit test

commit c76c618d16c9228e789c94b4b2be788e4db7465b
Author: Mark Forrer <mark.forrer@lbl.gov>
Date:   Thu Feb 13 13:24:04 2020 -0800

    Logging improvements as encountered

    Added a summary log at the beginning of processing an ED file or "Add line combos" request to help identify what input created it.  Removed per-line logging of blank rows in ED file parser and replaced with some simple code to log the range.  Real-world test file had hundreds of blank rows at the the end and a lot of unnecessary log messages.

commit 08bc2553354723de7c7a6217a26b721c87294071
Author: Mark Forrer <mark.forrer@lbl.gov>
Date:   Thu Feb 13 13:19:46 2020 -0800

    Fixed a TypeError triggered by testing "Add line combos" GUI

    TypeError: unhashable type: 'list'.  Still passing all previous tests.

commit c6bd9a8a85fe65b06cdac9192919f427c1144dc7
Author: Mark Forrer <mark.forrer@lbl.gov>
Date:   Thu Feb 13 13:16:21 2020 -0800

    Fix assay metadata handling in ED files

    Downstream Skyline imports using the new importer were failing because combinatorial assay time metadata values were stored as scalars, which caused the import's overwrite / duplication checks to fail when comparing scalar and vector time values for MeasurementValue.x.  As it turns out, the common assay metadata path (e.g. single time value per ED file row) was only working because those single scalar values were incorrectly stored in a list.    Corrected tracking in utilities.CombinatorialDescriptionInput for all assay metadata, and made analogous downstream changes in the importer code to wrap the scalar user inputs in lists before using them in import QuerySets.  Also did some minor / low-risk refactoring to add / correct type annotations and comments as encountered.  This commit successfully imports both the FBA tutorial data, some simplified single-time-per-row tests, and the original combinatorial dataset that caused the error.