Add forced python3.8 to flake8 commit hook
The pre-commit tool is having problems installing flake8 and its dependencies
with default Python (which is sometimes Python 3.9 and sometimes Python 3.10 on
my system at the moment). There were also some issues with black, which seem to
be resolved by re-installing Python 3.10. However, flake8 still has issues
regardless of re-installing Python.

The output from pre-commit installing the hook looks like the below:

    [INFO] Installing environment for https://github.com/pycqa/flake8.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    An unexpected error has occurred: CalledProcessError: command: ('/Users/wcmorrell/.cache/pre-commit/repoe97ie31x/py_env-default/bin/python', '-mpip', 'install', '.', 'flake8-bugbear')
    return code: 1
    expected return code: 0
    stdout:
        Processing /Users/wcmorrell/.cache/pre-commit/repoe97ie31x
          Preparing metadata (setup.py): started
          Preparing metadata (setup.py): finished with status 'done'
        Collecting flake8-bugbear
          Downloading flake8_bugbear-21.11.29-py36.py37.py38-none-any.whl (17 kB)

    stderr:
        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pyflakes/
        WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pyflakes/
        WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pyflakes/
        WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pyflakes/
        WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pyflakes/
        ERROR: Could not find a version that satisfies the requirement pyflakes<2.3.0,>=2.2.0 (from flake8) (from versions: none)
        ERROR: No matching distribution found for pyflakes<2.3.0,>=2.2.0

    Check the log at /Users/wcmorrell/.cache/pre-commit/pre-commit.log