Refactor async notification test handling
The tests for notifications started having some issues with timeouts after the
last downtime patching. One of the symptoms is having an async test fail with
the default timeout of one second, which then causes all subsequent tests to
fail as the event loop used for the first connection is reset. The errors in
the tests would look like this:

FAILED tests.py::test_A - AssertionError: Exceeded websocket timeout
FAILED tests.py::test_B - RuntimeError: <asyncio.locks.Lock object at 0x7f20267f0a50 [locked]> is bound to a different event loop
FAILED tests.py::test_C - RuntimeError: <asyncio.locks.Lock object at 0x7f20267f0a50 [locked]> is bound to a different event loop
FAILED tests.py::test_D - RuntimeError: <asyncio.locks.Lock object at 0x7f20267f0a50 [locked]> is bound to a different event loop
FAILED tests.py::test_E - RuntimeError: <asyncio.locks.Lock object at 0x7f20267f0a50 [locked]> is bound to a different event loop

The tests are now updated such that every test gets its own event loop, and the
ASGI application for notifications is initialized with that event loop. Also
added are a few helper classes for dealing with responses on updates to
notifications, so it's a little easier to read the test code and understand
what's going on with named functions instead of a bunch of nested key lookups
on the responses.

Reverting the 5 second timeouts. This will break tests on servers in the short
term, but we can just exclude the async tests temporarily to get around that.